version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "$PYTHON_VERSION"
        DJANGO_VERSION: "$DJANGO_VERSION"
        USE_S3: true
    # Note: collectstatic runs from inside the docker container and needs
    #       to access localstack through the host machine using host.docker.internal
    #       BUT when we access the django server from our host machine, we need to access
    #       the stored staticfiles via localhost, so export LOCALSTACK_HOST before and after
    command: >
      sh -c "export LOCALSTACK_HOST=localstack &&
             python tests/manage.py collectstatic --no-input &&
             export LOCALSTACK_HOST=localhost &&
             python tests/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - selenium
      - localstack
    environment:
      - LOCALSTACK_HOST=localstack
      - SELENIUM_HOST=host.docker.internal

  selenium:
    image: selenium/standalone-firefox
    network_mode: "host"
    ports:
      - "4444:4444" # Selenium
      - "5900:5900" # VNC
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=180
    volumes:
      - .:/code

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=true
      # enable persistence
      - PERSISTENCE=1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./create_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh"
